import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import PromoStrip from "@/components/layout/PromoStrip";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ChatFloatingButton from "@/components/layout/ChatFloatingButton";
import { Toaster } from "sonner";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Night Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${openSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <PromoStrip />
        <Toaster richColors position="bottom-center" />
        <main className="">
          {children}
        </main>
        <Footer />
        <ChatFloatingButton />
      </body>
    </html>
  );
}
